#ifndef INCLUDE_MACROS_H_
#define INCLUDE_MACROS_H_ 1


#define UNDEFINED_BUF 4
#define DEFINED_BUF 6
#define DEFAULT_BUFSZ 1
#define PERM 0666
#define MAX_BUF 1024
#define SLEEP_TIME 30000000

#endif // INCLUDE_MACROS_H_