#ifndef SERVER_MACROS_H_
#define SERVER_MACROS_H_ 1


#define UNDEF_BUFSZ 4
#define DEF_BUFSZ 6
#define DEFAULT_BUFSZ 1
#define PERM 0666
#define MAX_BUF 1024
#define SLEEP_TIME 30000000
#define TSKTIMEOUT -1

#endif // SERVER_MACROS_H_